export const data = {
    status: "OK",
    request_id: "2e346ba5-c36c-49e0-937f-35b16e4b67c3",
    parameters: {
        query: "sales developer in india",
        page: 1,
        num_pages: 1,
        date_posted: "all",
    },
    data: [
        {
            job_id: "0AhAN-ZoDd1HDDPMAAAAAA==",
            employer_name: "Amoga",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_NbxoHpTM3fw-MkloAYBpDkP2gHDcaBaMu2L7&s=0",
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "LinkedIn",
            job_employment_type: "FULLTIME",
            job_title: "SDR-Sales Development Representative",
            job_apply_link:
                "https://in.linkedin.com/jobs/view/sdr-sales-development-representative-at-amoga-3981809036?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6331,
            apply_options: [
                {
                    publisher: "LinkedIn",
                    apply_link:
                        "https://in.linkedin.com/jobs/view/sdr-sales-development-representative-at-amoga-3981809036?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "The ideal candidate is an energetic self-starter with the ability to identify influencers and key decision makers within accounts. You will discover qualified opportunities by responding to inbound interests and targeted outbound prospects to build rapport and establish long-term relationships.\n\nResponsibilities\n• Drive top-of-the-funnel lead generation for account executives and sales managers\n• Update and manage all sales activities, opportunities, and account information in CRM\n• Consistently achieve monthly quota of qualified opportunities\n\nQualifications\n• Bachelor's degree in Business or a related field\n• At least 1 - 2 years' of relevant work experience\n• Excellent written and verbal communication skills\n• Ability to multi-task, organize, and prioritize work",
            job_is_remote: false,
            job_posted_at_timestamp: 1722412427,
            job_posted_at_datetime_utc: "2024-07-31T07:53:47.000Z",
            job_city: "Bengaluru",
            job_state: "KA",
            job_country: "IN",
            job_latitude: 12.971599,
            job_longitude: 77.59457,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3D0AhAN-ZoDd1HDDPMAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2025-01-27T07:53:29.000Z",
            job_offer_expiration_timestamp: 1737964409,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: "12",
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: null,
            job_required_education: {
                postgraduate_degree: "false",
                professional_certification: "false",
                high_school: "true",
                associates_degree: "false",
                bachelors_degree: "false",
                degree_mentioned: "true",
                degree_preferred: "true",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Development representative",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "sA-BE-FoHYAyYcm9AAAAAA==",
            employer_name: "Intugine - Logistics through Innovation",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnfQ6374rc1t_mq_tyl5NriituMul6dk5UBar6&s=0",
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "LinkedIn",
            job_employment_type: "FULLTIME",
            job_title: "Sales Development Representative",
            job_apply_link:
                "https://in.linkedin.com/jobs/view/sales-development-representative-at-intugine-logistics-through-innovation-3971431545?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.7466,
            apply_options: [
                {
                    publisher: "LinkedIn",
                    apply_link:
                        "https://in.linkedin.com/jobs/view/sales-development-representative-at-intugine-logistics-through-innovation-3971431545?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "HR Software For Growing Businesses | Freshteam",
                    apply_link:
                        "https://intugine.freshteam.com/jobs/7Ueqf2eG7iZ4/sales-development-representative?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "Foundit.in",
                    apply_link:
                        "https://www.foundit.in/job/sales-development-representative-intugine-logistics-through-innovation-bengaluru-bangalore-30811450?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "BeBee India",
                    apply_link:
                        "https://in.bebee.com/job/8733c6272ea2626af4ae28e09d453a80?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "Talent.com",
                    apply_link:
                        "https://in.talent.com/view?id=ba0e128a014d&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "Jobs Trabajo.org",
                    apply_link:
                        "https://in.trabajo.org/job-1525-24e176ccec88ae8984879452099da225?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "Jobrapido.com",
                    apply_link:
                        "https://in.jobrapido.com/jobpreview/305407599?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "ZipRecruiter India",
                    apply_link:
                        "https://www.ziprecruiter.in/jobs/333498808-sales-development-representative-at-intugine-technologies?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "About Intugine\n\nEver wondered how the physical goods we consume every day (think dairy, snacks, or your favourite choco chip ice cream) reach you in time? Or how beautiful furniture or sophisticated electronic equipment and gadgets you use are delivered in the best possible condition at your doorstep.\n\nTheir journey spans from getting sourced, manufactured, and stored, to getting moved across a highly intricate supply chain network across the globe before it gets delivered. Global brands constantly face challenges like not having visibility of their raw materials, which delays production and in turn, delays customer shipments, or tracking shipments across various modalities and multiple geographies.\n\nIntugine Technologies is one of the most trusted solution partners catering to these brands with its best-in-class visibility platform helping brands gain comprehensive visibility over their supply chain across modalities(air/land/sea/rail). Their solutions have helped eliminate operational inefficiencies, reduce logistics costs and improve OTIF, order to delivery TAT, and minimise dwell time and detention costs.\n\nIntugine is a proud partner of the National Logistics Policy, an initiative by the Government of India. With this, it provides these brands with additional information via their integrations with FASTag, Port Community System, and Freight Operations Information System to name a few.\n\nToday Intugine works with 75+ global enterprise names like GE Healthcare, Signify, Flipkart, Mahindra Logistics, Titan, Diageo, Ultratech Cement, Bridgestone, and GMMCO.\n\nTo know more, visit the website: https://www.intugine.com\n\nRole and Function:\n\nWe are looking to expand our Business Development team with kickass Sales Development Representatives (SDRs). The SDRs shall play a critical role to achieve our ambitious customer acquisition and revenue growth objectives. Being the first point of contact for all the outbound engagements with Prospects, the SDRs will be thoroughly responsible for the addition of new accounts into the Sales Funnel.\n\nWho makes a Great Fit?\n• 1+ year experience in Lead Generation/Customer Facing Roles\n• Experience in SaaS is a Plus.\n• Experience in IoT/Technology is a Plus Plus.\n• Experience in Logistics and Supply Chain is a Plus Plus Plus (Apply already, will ya?).\n• Great Communication Skills (Verbal and Written - Emails, LinkedIn and WhatsApp)\n• Quick Learner, Go-getter, Self Starter.\n• Basic Understanding of Sales and Lead Generation Process, Contact Extraction Tools, and LinkedIn.\n• Experience working with Hubspot or similar CRM\n• Ability to effectively communicate with decision makers and end users.\n• Multilingual proficiency - English, Hindi\n• Problem-solving aptitude\n• Strong phone presence and comfortable making several calls during the day\n\nResponsibilities:\n• Research Key Accounts in the Target Industry and map Decision Makers in each account.\n• Maintain and expand the Company's database of prospects within the assigned territory.\n• Go Hammer and Tongs in extracting Contact Details of the prospects from various tools.\n• Effectively establish the first level of connection with the Decision Makers through email/LinkedIn/Calls.\n• Qualify Prospect requirements, map the requirements to Intugine’s product offerings, schedule VCs, and route the opportunity to Account Executives.\n• Maintain a healthy pipeline of prospects on CRM throughout.\n• Owning and exceeding sales development targets.\n• Your targets shall be based on the number of meetings you set and the number of Sales Qualified meetings you generate. You shall be rewarded handsomely/beautifully (because gender-neutral!!) for meeting & overachieving your Targets.\n• Constantly evaluate for Sales Enablement tools to potentially pace up unlocking new opportunities.\n\nOur team comprises of ambitious, reliable, and witty people who love to play around; while getting the job done. We are looking for smart and adventurous people who relish an opportunity to solve intricate problems. If you want to make an impact with your work, then Intugine is the right place for you.\n\nPerks at Intugine:\n\nLooking for more reasons to join the Intugine rocketship? We’ll give you 13!\n• Employee Stock Options -Take a slice of the pie and grow with us\n• Comprehensive Health Cover - For you\n• Personal Development Budget- Upskill yourself, we’ve got the bill\n• Flexible Working Hours - Set your own work hours\n• Open door policy - No to cubicles. Yes to the Open door policy.\n• Generous Parental Leave - Cause work comes second sometimes\n• Documented Equal Pay Policy - Since we’re in 2024!\n• Education Assistance - Let us help you soar to new heights\n• Work Autonomy - Enjoy complete ownership over your work\n• Employee Life Skill Training Program - Regular sessions on tax saving, investments, mental well-being, health and Fitness etc.\n• Company Outings - Unwind with teammates. Work can wait.\n• Paid time off - Because your well-being is our priority",
            job_is_remote: false,
            job_posted_at_timestamp: 1720626271,
            job_posted_at_datetime_utc: "2024-07-10T15:44:31.000Z",
            job_city: "Bengaluru",
            job_state: "KA",
            job_country: "IN",
            job_latitude: 12.971599,
            job_longitude: 77.59457,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DsA-BE-FoHYAyYcm9AAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2024-08-09T15:44:31.000Z",
            job_offer_expiration_timestamp: 1723218271,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: "12",
                experience_mentioned: "true",
                experience_preferred: "true",
            },
            job_required_skills: null,
            job_required_education: {
                postgraduate_degree: "false",
                professional_certification: "false",
                high_school: "true",
                associates_degree: "false",
                bachelors_degree: "false",
                degree_mentioned: "false",
                degree_preferred: "false",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Development representative",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "I_Xj2kqVSY-uvLFxAAAAAA==",
            employer_name: "Crimson Education",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXF59cwhTv1GE-PowgyEPGr_1W62d_2oIdD3BK&s=0",
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "Crimson Education",
            job_employment_type: "FULLTIME",
            job_title: "Sales Development Representative",
            job_apply_link:
                "https://jobs.crimsoneducation.org/jobs/2842812-sales-development-representative?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.782,
            apply_options: [
                {
                    publisher: "Crimson Education",
                    apply_link:
                        "https://jobs.crimsoneducation.org/jobs/2842812-sales-development-representative?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "Want to revolutionize the future of education and do meaningful work that transforms future generations’ lives?\n\nEdTech company Crimson Education was founded in 2013 from the idea that through personalised education, we can transform students into the world leaders of tomorrow. Since then, we have rapidly grown a mission-driven team that is dedicated to building the education system for the 22nd century. Our network includes 2,400 tutors and consultants worldwide who work with over 20,000 students.\n\nOur tech platform connects tutors and mentors to high school students aiming to achieve admission and scholarships to top universities in the US, Canada, UK, and beyond.\n\nThis is a full-time position, based in India\n\nThe ideal candidate will be able to build rapport easily, be customer-obsessed, and have a growth mindset.\n\nThe purpose of this role is to be the first point of contact for incoming leads and potential clients, ensuring a smooth customer experience across a variety of Crimson programs, by:\n• Managing, contacting, and qualifying inbound warm/hot leads to Crimson Turkey\n• Providing resources to leads to inform them of opportunities with Crimson\n• Working as part of a high performing team to provide the best experience to potential Crimson students\n\nWhat are the main responsibilities for this role?\n• Making calls and responding to enquiries from leads to qualify them for sales processes, ensuring that data is diligently, accurately entered and managed within Crimson’s Client Relations Management (CRM) system Salesforce\n• Updating the record of these leads and tracking their movements to the next stage of the sales pipeline in Salesforce\n• Track Crimson events and plan accordingly to reach out to the event leads\n• Schedule meetings for the leads to meet with Crimson’s Academic Advisors and Country Manager\n• Planning and running local events to increase brand awareness for Crimson\n• Establish, develop and maintain positive and professional customer interactions and relationships for Crimson\n• Continuously improving sales techniques, processes and enhancing industry knowledge\n• Engaging in outreach activities such as presenting at school talks, careers expos, and Crimson seminars when required\n• Attending industry events as required\n• Collating fortnightly sales reports in an accurate and concise manner for management\n\nWhat skills and experience are required?\n• Proficient in English - Spoken/Written\n• Experience in Customer Service, Customer Success\n• Experience in university admissions (US & UK as priority) will be preferred but not required\n• Excellent communication skills\n• Excellent organisation skills\n• Professionalism, Time and Stress Management, Confidence, Positive attitude (patience, empathy), Willingness to learn and go the extra mile\n• Experience in the Education or professional services (e.g. marketing agency, financial services, management consulting, hospitality, etc.) sector and using CRM (Salesforce) and multiple systems and platforms\n\nWhy work for Crimson?\n• Flexible working environment, you will be empowered to structure how you work\n• Option to work from our many locations/remotely around the globe (role dependant) with us!\n• Limitless development and exposure- our internal promotions/role changes made up 33% of all recruitment last year.\n• $1,000 training budget per year- we love to level up!\n• Psychologist on staff\n• Impressive fireside chats and workshops to help the team continuously level up\n• Radical Candour is a feedback approach we live by\n• We’re a global player with 28 markets (and growing) across the globe!\n\nIf you're passionate about education and people and looking for a fast-paced, collaborative environment, and want to work with cutting-edge technology then we'd love to hear from you!\n\nPlease keep an eye on your spam / junk email folder for correspondence from Team Tailor.",
            job_is_remote: false,
            job_posted_at_timestamp: 1684457097,
            job_posted_at_datetime_utc: "2023-05-19T00:44:57.000Z",
            job_city: "Kora",
            job_state: "MH",
            job_country: "IN",
            job_latitude: 20.624517,
            job_longitude: 79.04191,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DI_Xj2kqVSY-uvLFxAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: null,
            job_offer_expiration_timestamp: null,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: null,
                experience_mentioned: "true",
                experience_preferred: "true",
            },
            job_required_skills: null,
            job_required_education: {
                postgraduate_degree: false,
                professional_certification: false,
                high_school: false,
                associates_degree: false,
                bachelors_degree: false,
                degree_mentioned: "false",
                degree_preferred: "false",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Development representative",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "gO7vAG0Bj3N06vFRAAAAAA==",
            employer_name: "One Digital Entertainment",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeNpTd7pecd5ejbEq-Vk3J8XvgONx0RZaCcHvM&s=0",
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "LinkedIn",
            job_employment_type: "FULLTIME",
            job_title: "Media Sales",
            job_apply_link:
                "https://in.linkedin.com/jobs/view/media-sales-at-one-digital-entertainment-3987963179?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6515,
            apply_options: [
                {
                    publisher: "LinkedIn",
                    apply_link:
                        "https://in.linkedin.com/jobs/view/media-sales-at-one-digital-entertainment-3987963179?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "Job Description:\n• Minimum 1-2 yrs experience from the Media/ Entertainment industry (TV, property, In-film Sales).\n• Candidates should have an understanding of creators, brand partnerships, Brand Endorsements, Influencer Marketing & Branded Content.\n• A commercially astute and customer-focused individual, with a solid sales track record and a proven ability to foster strong business relationships.\n• Experience in Sales in the areas of endorsements for celebrities & movie marketing and sponsorships for events is essential.\n• Should be able to identify, qualify and secure business opportunities by cultivating and maintaining mutually beneficial business relationships with current and potential clients.\n• Following up new business opportunities and setting up meetings.\n• Communicating new product developments to prospective clients.\n\nSkills and Interests:\n• Understanding about their market and competitors' products.\n• Good communications skills, both written and verbal.\n• To be self-motivated but able to work as part of a team.\n• A positive attitude.\n• Good negotiation skills and persuasiveness.\n• Confidence in presenting to large groups of people.\n• Provide constant brand updates of the particular category/region (through research/website/social media/print media)\n\nQualifications:\n• Bachelor's degree or equivalent experience in Business\n• 3+ years' of sales or account management experience\n• Excellent written and verbal communication skills",
            job_is_remote: false,
            job_posted_at_timestamp: 1722501205,
            job_posted_at_datetime_utc: "2024-08-01T08:33:25.000Z",
            job_city: "Mumbai",
            job_state: "MH",
            job_country: "IN",
            job_latitude: 19.075983,
            job_longitude: 72.877655,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DgO7vAG0Bj3N06vFRAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2024-08-31T08:33:25.000Z",
            job_offer_expiration_timestamp: 1725093205,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: "36",
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: [
                "Media Sales",
                "Account Management",
                "Digital Media",
                "Marketing",
                "Advertising Sales",
                "Business Development",
                "Media Planning",
                "Sales",
                "New Business Development",
                "Online Advertising",
            ],
            job_required_education: {
                postgraduate_degree: "false",
                professional_certification: "false",
                high_school: "false",
                associates_degree: "false",
                bachelors_degree: "true",
                degree_mentioned: "true",
                degree_preferred: "false",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: null,
            job_posting_language: "en",
            job_onet_soc: "41301100",
            job_onet_job_zone: "4",
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "82zqtZ8uLbrv0eUnAAAAAA==",
            employer_name: "Apna",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHAiVGWPC2Oozchzz2YdHqaLiuRfUNPca5F7xo&s=0",
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "GSV Ventures Job Board",
            job_employment_type: "FULLTIME",
            job_title: "Sales Development Representative",
            job_apply_link:
                "https://gsv.getro.com/companies/apna/jobs/37982562-sales-development-representative?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6576,
            apply_options: [
                {
                    publisher: "GSV Ventures Job Board",
                    apply_link:
                        "https://gsv.getro.com/companies/apna/jobs/37982562-sales-development-representative?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "BeBee India",
                    apply_link:
                        "https://in.bebee.com/job/49e18f1b7f69b1ad4a1afb823ff3a172?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "Trabajo.org",
                    apply_link:
                        "https://in.trabajo.org/job-1525-ef94deddc0d0be1f3f753326a564c589?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "Expertini | India Jobs Expertini",
                    apply_link:
                        "https://in.expertini.com/jobs/job/sales-development-representative-bengaluru-apna-bbc2b09990/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
                {
                    publisher: "Elsejob",
                    apply_link:
                        "https://www.elsejob.com/jobdetails/sales-development-representative-job2024020213784/139853.html?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "We are looking for a Sales Development Representative (SDR) to join our sales team. The ideal candidate will have 0-4 years of SDR experience and a track record of successfully targeting HR personas in their previous roles. The SDR will play a crucial role in generating new business opportunities for Apna by identifying and reaching out to potential HRs in the industry.\n\nResponsibilities:\n• Prospect and qualify potential leads through outbound calls, emails, and social media outreach\n• Research and identify key decision-makers within target companies, primarily in the HR department\n• Conduct initial conversations with potential clients to understand their hiring needs and pain points\n• Communicate the value proposition of Apna's HR tech solutions effectively\n• Schedule qualified meetings and product demos for the sales team\n• Collaborate with the sales and marketing teams to develop and refine lead generation strategies\n• Maintain accurate records of interactions and activities in the CRM system\n• Stay updated on industry trends and best practices in HR technology\n\nRequirements\n• Bachelor's degree in Business, Marketing, or a related field is preferred\n• Excellent verbal and written communication skills in English\n• Fluent in Hindi\n• 3+ years of experience in a Sales Development Representative (SDR) role\n• Strong interpersonal skills and the ability to build rapport with potential clients\n• Proactive and self-motivated with a strong desire to achieve sales targets\n• Familiarity with CRM software (e.g., FreshSales) is a plus\n• Adept at using sales and marketing tools such as LinkedIn Sales Navigator\n• Highly organized and able to manage time effectively\n• Goal-oriented with a competitive spirit\n• Most importantly, high on energy and does not take ‘no' for an answer\n• Preferred: Prior experience targeting HR personas within target companies is highly preferable",
            job_is_remote: false,
            job_posted_at_timestamp: 1719069083,
            job_posted_at_datetime_utc: "2024-06-22T15:11:23.000Z",
            job_city: "Bengaluru",
            job_state: "KA",
            job_country: "IN",
            job_latitude: 12.971599,
            job_longitude: 77.59457,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3D82zqtZ8uLbrv0eUnAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2024-10-27T00:00:00.000Z",
            job_offer_expiration_timestamp: 1729987200,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: "36",
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: null,
            job_required_education: {
                postgraduate_degree: false,
                professional_certification: false,
                high_school: false,
                associates_degree: false,
                bachelors_degree: false,
                degree_mentioned: "true",
                degree_preferred: "true",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Development representative",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "nOghjUzCHP6WwH5jAAAAAA==",
            employer_name: "Staffing Support India",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_ojT4nA4DZyxhSqgT8zzSPm0T90N5Zqgqy5rz&s=0",
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "LinkedIn",
            job_employment_type: "FULLTIME",
            job_title: "Telesales Representative",
            job_apply_link:
                "https://in.linkedin.com/jobs/view/telesales-representative-at-staffing-support-india-3988714113?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6456,
            apply_options: [
                {
                    publisher: "LinkedIn",
                    apply_link:
                        "https://in.linkedin.com/jobs/view/telesales-representative-at-staffing-support-india-3988714113?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "Job Description : Tele Sales Associate\n\nLocation: Kirti Nagar Industrial Area, New Delhi\n\nType: Full-time\n\nWork from Office\n\nUS SHIFT // NIGHT SHIFT\n\nAbout the Job :\n\nWe are looking for a Sales Person for our well-established organisation, a fragrance brand in the US. The timing will be US based (night shift).\n\nSalary : 3.5L - 5.5L PA\n\nQualifications :\n• Bachelor's degree in any field\n• Minimum 3 years experience in Sales\n• Minimum 2 years experience in International tele-sales\n\nSkills Required :\n• Strong oral and written communications skills\n• Persuasive skills\n• Active listening skills\n• Rapport building skills\n• Proven track record of achieving significant revenue growth through innovative selling tactics.\n• Excellent communication skills for building strong relationships with customers at all levels.\n• Strong communication skills with ability to handle cold calling situations effectively.\n• Must know how to work on Amazon, Ebay & Walmart\n• Email marketing\n\nResponsibilities :\n• Primary task is to do sales via call , email , chat , third party websites\n• Contact existing and potential customers to generate sales.\n• Make outbound calls to clients to generate leads and convert them into paying customers.\n• Develop and execute regional sales strategies to achieve business objectives.\n• Meet daily/weekly targets set by the management while ensuring quality standards are met.\n• Developing in-depth knowledge of product features and benefits.\n• Manage email blasts\n\nBenefits :\n• Competitive salary with opportunities for advancement.\n• Professional development opportunities in a thriving industry.\n• We are an equal opportunity employer, committed to fostering an inclusive and diverse workforce.\n• Join us in contributing to the continued success of our dynamic organisation!",
            job_is_remote: false,
            job_posted_at_timestamp: 1722448571,
            job_posted_at_datetime_utc: "2024-07-31T17:56:11.000Z",
            job_city: "New Delhi",
            job_state: "DL",
            job_country: "IN",
            job_latitude: 28.61393,
            job_longitude: 77.20883,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DnOghjUzCHP6WwH5jAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2024-08-30T17:56:11.000Z",
            job_offer_expiration_timestamp: 1725040571,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: "36",
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: [
                "Sales Processes",
                "Written Communication",
                "Active Listening",
                "Telemarketing",
                "Sales",
                "Cold Calling",
                "Communication",
                "Product Knowledge",
                "Customer Experience",
                "Persuasive Speaking",
            ],
            job_required_education: {
                postgraduate_degree: "false",
                professional_certification: "false",
                high_school: "true",
                associates_degree: "false",
                bachelors_degree: "false",
                degree_mentioned: "true",
                degree_preferred: "true",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Representative",
            job_posting_language: "en",
            job_onet_soc: "41904100",
            job_onet_job_zone: "2",
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "CUbxRjYsykfffKtpAAAAAA==",
            employer_name: "Koot",
            employer_logo: null,
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "Truemote",
            job_employment_type: "FULLTIME",
            job_title: "Business Development Representative",
            job_apply_link:
                "https://truemote.com/remote-job/remote-business-development-representative-b28bdd/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.3932,
            apply_options: [
                {
                    publisher: "Truemote",
                    apply_link:
                        "https://truemote.com/remote-job/remote-business-development-representative-b28bdd/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "Company Description\n\nKoot is a company that assists SaaS startups in growing through partnership channels. We identify the most suitable partnership types based on various parameters like customer persona, ARR per customer, stickiness, industry, and geography. Our hands-on approach involves creating partner programs, defining potential partner channels after thorough research, recruiting partners, and supporting your team in building relationships, generating pipeline, and achieving revenue targets.\n\nRole Description\n\nThis is a full-time remote role for a Business Development Representative at Koot. The role involves tasks such as inside sales, lead generation, effective communication, sales activities, and business development strategies to increase partnerships and revenue.\n\nQualifications\n• Inside Sales and Lead Generation skills\n• Effective Communication skills\n• Sales and Business Development expertise\n• Ability to build and maintain strong relationships\n• Experience in creating and implementing sales strategies\n• Knowledge of the SaaS industry and partnership channels\n• Proven track record of meeting and exceeding sales targets\n• Bachelor’s degree in Business Administration, Marketing, or related field",
            job_is_remote: true,
            job_posted_at_timestamp: 1722396174,
            job_posted_at_datetime_utc: "2024-07-31T03:22:54.000Z",
            job_city: null,
            job_state: null,
            job_country: "IN",
            job_latitude: 20.593683,
            job_longitude: 78.96288,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DCUbxRjYsykfffKtpAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2024-08-07T03:22:54.000Z",
            job_offer_expiration_timestamp: 1723000974,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: null,
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: null,
            job_required_education: {
                postgraduate_degree: false,
                professional_certification: false,
                high_school: false,
                associates_degree: false,
                bachelors_degree: false,
                degree_mentioned: "true",
                degree_preferred: "true",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Development representative",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "tZ4KBTGll7IpT81HAAAAAA==",
            employer_name: "AdAired Digital Media",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRB2bxaYILtH0IeEajyAUXpUQ-zXmAmD10-XGh&s=0",
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "LinkedIn",
            job_employment_type: "FULLTIME",
            job_title: "Business Development Executive",
            job_apply_link:
                "https://in.linkedin.com/jobs/view/business-development-executive-at-adaired-digital-media-3987940839?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6506,
            apply_options: [
                {
                    publisher: "LinkedIn",
                    apply_link:
                        "https://in.linkedin.com/jobs/view/business-development-executive-at-adaired-digital-media-3987940839?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "Roles and Responsibilities :-\n\n● Develops sales opportunities by researching and identifying potential accounts, soliciting\n\nnew accounts, building rapport, providing technical information and explanations, and\n\npreparing quotations.\n\n● Develop and execute lead generation campaigns that support business objectives,\n\nincluding the creation of targeted lists, email, web, and social media outreach.\n\n● Work with the marketing team to create high-quality content that will be used in lead\n\ngeneration campaigns.\n\n● Manage budget for lead generation campaigns and track ROI\n\n● Stay up-to-date on latest lead generation practices and tools\n\n● Source new sales opportunities through inbound lead follow-up and outbound cold calls\n\nand emails.\n\n● Schedule a meeting by maintaining all the call quality parameters and understand\n\ncustomer needs and requirements.\n\n● Close sales and achieve quarterly quotas.\n\n● Assesses competitors by analyzing and summarizing competitor information and trends\n\nand identifying sales opportunities.\n\n● Research accounts, identify key players, and generate interest.\n\n● Maintain and expand your database of prospects within your assigned territory.\n\n● Perform effective online demos to prospects.\n\nSkills Required :-\n\n● BA/BS degree or equivalent.\n\n● Proven inside sales experience at least 2 years, in Digital Marketing\n\n● Track record of over-achieving quota.\n\n● Strong phone presence and experience in B2B US sales.\n\n● Proficient with corporate productivity and web presentation tools.\n\n● Experience working with ZOHO or similar CRM.\n\n● Excellent verbal and written communication skills.\n\n● Strong listening and presentation skills.\n\n● Ability to multitask, priorities, and manage time effectively.",
            job_is_remote: false,
            job_posted_at_timestamp: 1722496389,
            job_posted_at_datetime_utc: "2024-08-01T07:13:09.000Z",
            job_city: "Sahibzada Ajit Singh Nagar",
            job_state: "PB",
            job_country: "IN",
            job_latitude: 30.704649,
            job_longitude: 76.71787,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3DtZ4KBTGll7IpT81HAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2025-01-28T07:13:09.000Z",
            job_offer_expiration_timestamp: 1738048389,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: "24",
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: null,
            job_required_education: {
                postgraduate_degree: "false",
                professional_certification: "false",
                high_school: "false",
                associates_degree: "false",
                bachelors_degree: "true",
                degree_mentioned: "true",
                degree_preferred: "true",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: null,
            job_max_salary: null,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Development executive",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "h_nGQ9NbgLNPziyqAAAAAA==",
            employer_name: "LimeTray",
            employer_logo:
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdSGghlnsMxNBhf0PZm2-qewMg2ydQAMLw1i06&s=0",
            employer_website: "http://limetray.com",
            employer_company_type: null,
            employer_linkedin: "https://www.ynos.in/startup/alchemy-web-0116",
            job_publisher: "Internshala",
            job_employment_type: "FULLTIME",
            job_title:
                "Sales Development Representative/Inside Sales Manager Fresher Job",
            job_apply_link:
                "https://internshala.com/job/detail/fresher-sales-development-representative-inside-sales-manager-job-in-gurgaon-at-limetray1722334088?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: false,
            job_apply_quality_score: 0.6113,
            apply_options: [
                {
                    publisher: "Internshala",
                    apply_link:
                        "https://internshala.com/job/detail/fresher-sales-development-representative-inside-sales-manager-job-in-gurgaon-at-limetray1722334088?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "About the job:\nLimeTray is a leading B2B SaaS company specializing in providing comprehensive technology solutions for the food industry, including restaurants, cafes, and food businesses. Our product suite includes advanced Point of Sale (POS) systems, website and mobile application development, digital solutions, and more. Our goal is to empower our clients with innovative tools to streamline their operations and enhance their customer experience.\n\nFor more information, please visit: https://limetray.com\n\nWe're looking to add innovative, ambitious, passionate, and energetic individuals across various functions of the company to help us meet and exceed our business objectives. As an 'Inside Sales Manager', you will play a crucial role in driving our sales efforts and expanding our customer base in existing and new markets.\n\nKey Responsibilities:\n\n1. Drive sales of LimeTray products & services to the Indian market.\n\n2. Identify key decision-makers within target organizations and engage in strategic, consultative conversations to understand their business needs.\n\n3. Conduct product demonstrations and presentations to potential clients, effectively communicating the value proposition and benefits of our products and services.\n\n4. Develop and maintain strong relationships with prospects and clients through regular follow-ups, addressing their inquiries, and providing accurate information about our offerings.\n\n5. Meet or exceed monthly and quarterly sales targets and contribute to the overall revenue growth of the company.\n\n6. Stay up-to-date with industry trends, competitors, and market conditions to identify opportunities and make recommendations for sales strategies.\n\n7. Utilize CRM software to manage and track leads, opportunities, and sales activities accurately.\n\n8. Collaborate with cross-functional teams, including key account managers, project managers, technical leads, and executives, to ensure smooth handover of projects from sales to delivery teams.\n\n9. Provide timely and accurate sales reports, forecasts, and market feedback to the management team.\n\nLocation: Udyog Vihar Phase 5, Sector 19, Gurgaon (On-site/hybrid)\n\nIf you are a dynamic and results-driven sales professional with a proven track record in inside sales management, we want to hear from you. Join LimeTray and take your career to the next level in a fast-paced and exciting work environment. Apply now and be part of our success story!\n\n1. Those who are from or open to relocate to Gurgaon and neighboring cities\n\nDeadline:\n2024-08-29 23:59:59\n\nOther perks:\n5 days a week, Health Insurance\n\nSkills required:\nSales and Sales pitch\n\nAbout Company:\nWe, at LimeTray, have decided to help restaurants by designing and implementing products that help bridge the disconnect between restaurants & the consumer. In a world that demands convenience, we help restaurants get online and provide them with tools to engage with customers, increase their reach, and improve their operational efficiency.",
            job_is_remote: false,
            job_posted_at_timestamp: 1722297600,
            job_posted_at_datetime_utc: "2024-07-30T00:00:00.000Z",
            job_city: "Gurugram",
            job_state: "HR",
            job_country: "IN",
            job_latitude: 28.459497,
            job_longitude: 77.02664,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3Dh_nGQ9NbgLNPziyqAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2024-08-29T00:00:00.000Z",
            job_offer_expiration_timestamp: 1724889600,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: null,
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: ["Sales Sales pitch"],
            job_required_education: {
                postgraduate_degree: false,
                professional_certification: false,
                high_school: false,
                associates_degree: false,
                bachelors_degree: false,
                degree_mentioned: "false",
                degree_preferred: "false",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: false,
            job_min_salary: 300000,
            job_max_salary: 400000,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Sales manager",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
        {
            job_id: "1ZuXF5hXbEUwWzmSAAAAAA==",
            employer_name: "OpenIntervue",
            employer_logo: null,
            employer_website: null,
            employer_company_type: null,
            employer_linkedin: null,
            job_publisher: "Glassdoor",
            job_employment_type: "FULLTIME",
            job_title: "Sales Development Representative",
            job_apply_link:
                "https://www.glassdoor.co.in/job-listing/sales-development-representative-openintervue-JV_IC2940587_KO0,32_KE33,45.htm?jl=1009382137152&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
            job_apply_is_direct: true,
            job_apply_quality_score: 0.5721,
            apply_options: [
                {
                    publisher: "Glassdoor",
                    apply_link:
                        "https://www.glassdoor.co.in/job-listing/sales-development-representative-openintervue-JV_IC2940587_KO0,32_KE33,45.htm?jl=1009382137152&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: true,
                },
                {
                    publisher: "SimplyHired",
                    apply_link:
                        "https://www.simplyhired.co.in/job/69m62mp1Hu3c_mLpsIMm-Eu2pkuZnr-5z1F-GptYZmYIWuJLxcl9aw?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
                    is_direct: false,
                },
            ],
            job_description:
                "Job Title: Sales Development Representative\n\nCompany Overview:\n\nOpenIntervue is revolutionizing the recruitment process with the use of AI, ML, and NLP technologies to conduct automated interviews without human involvement. It offers innovative solutions for smart recruitment, standardization, and fairness in the hiring process. OpenIntervue provides scalability, cost savings, higher productivity, and advanced AI capabilities tuned for various industries such as BPOs, IT, Healthcare, Banking, Telecom, Pharma, FMCG, Travel, and Retail.\n\nJob Summary:\n\nAs a Sales Development Representative at OpenIntervue, you will play a crucial role in scaling the business by finding the right talent through AI-driven interviews. You will be responsible for promoting the benefits of OpenIntervue's automated interview system to potential clients and showcasing how it can streamline their recruitment processes.\n\nKey Responsibilities:\n\n- Act as the primary point of contact for potential clients interested in OpenIntervue's solutions.\n\n- Educate and demonstrate the features and benefits of OpenIntervue to prospects through effective sales techniques.\n\n- Qualify leads and set up product demonstrations to showcase the capabilities of OpenIntervue's automated interview system.\n\n- Collaborate with the marketing team to develop targeted outreach campaigns and strategies that drive lead generation.\n\n- Develop a deep understanding of client needs and effectively communicate how OpenIntervue can address their recruitment challenges.\n\nSkills:\n\n- Proven experience in sales or business development roles.\n\n- Excellent communication and interpersonal skills for building relationships with potential clients.\n\n- Strong problem-solving abilities to understand client pain points and propose effective solutions using OpenIntervue's offerings.\n\n- Familiarity or experience with AI-driven technologies would be an advantage.\n\nAttributes and Traits:\n\n- Results-driven with a strong focus on achieving sales targets and driving business growth.\n\n- Self-motivated individual with exceptional time management skills.\n\n- Adaptability to work in a dynamic startup environment driven by innovation and technology advancements.\n\n- Team player with a collaborative mindset who thrives in a fast-paced entrepreneurial culture.\n\nBenefits and Perks:\n\n- Competitive salary package along with performance-based incentives.\n\n- Opportunity to be part of an innovative company that is transforming traditional hiring methods through cutting-edge technology.\n\nJob Type: Full-time\n\nPay: ₹50,000.00 - ₹75,000.00 per month\n\nJadwal:\n• Day shift\n• Morning shift\n\nTunjangan:\n• Cell phone reimbursement\n\nExperience:\n• Cold calling: 1 year (Preferred)\n• total work: 1 year (Preferred)\n• Sales: 1 year (Preferred)\n• sales representative: 1 year (Preferred)\n\nLanguage:\n• English (Preferred)\n\nWork Location: In person\n\nSpeak with the employer\n+91 8095133688\nApplication Deadline: 10/08/2024",
            job_is_remote: false,
            job_posted_at_timestamp: 1721952000,
            job_posted_at_datetime_utc: "2024-07-26T00:00:00.000Z",
            job_city: "Bengaluru",
            job_state: "KA",
            job_country: "IN",
            job_latitude: 12.971599,
            job_longitude: 77.59457,
            job_benefits: null,
            job_google_link:
                "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=sales+developer+in+india&start=0&udm=8#vhid=vt%3D20/docid%3D1ZuXF5hXbEUwWzmSAAAAAA%3D%3D&vssid=jobs-detail-viewer",
            job_offer_expiration_datetime_utc: "2024-11-25T00:00:00.000Z",
            job_offer_expiration_timestamp: 1732492800,
            job_required_experience: {
                no_experience_required: "false",
                required_experience_in_months: null,
                experience_mentioned: "true",
                experience_preferred: "false",
            },
            job_required_skills: null,
            job_required_education: {
                postgraduate_degree: false,
                professional_certification: false,
                high_school: false,
                associates_degree: false,
                bachelors_degree: false,
                degree_mentioned: "false",
                degree_preferred: "false",
                professional_certification_mentioned: "false",
            },
            job_experience_in_place_of_education: "false",
            job_min_salary: 50000,
            job_max_salary: 75000,
            job_salary_currency: null,
            job_salary_period: null,
            job_highlights: {},
            job_job_title: "Development representative",
            job_posting_language: "en",
            job_onet_soc: "41401400",
            job_onet_job_zone: null,
            job_occupational_categories: null,
            job_naics_code: null,
            job_naics_name: null,
        },
    ],
};
